language: nix
matrix:
    include:
        - os: linux
          sudo: true
          before_script:
              - git clone -b unstable --depth=50 https://github.com/offlinehacker/nixpkgs
          scripts:
              - nix-build -I nixos-config=$PWD/configurations/dev.nix -A config.system.build --argstr system x86_64-linux $PWD/nixpkgs/nixos 
