sudo: true
language: generic
dist: bionic
nix: 2.3.3

jobs:
    include:
        - stage: Build
          env: TARGET=images.hyperv-image
        - env: TARGET=images.iso-dev
        - stage: Release
          if: tag IS present
          env: TARGET=images.all
          deploy:
            provider: releases
            api_key:
                secure: CxAUzq1W9xOc4s5Ca2TovyPoXxXQytkx/++FIx4HCXYvrJVvNZv+w9e4CHLvTMDfUfC0FuFs4EAyy9WARcjELdD1RYkseX6C33jEm5g1lzwq4lFfEUVKoTEOoZWh47ykt1kUjlfK/joHOjnEoZCm5hIyil2JBql94v3AwozJcmg=
            file_glob: true
            file: result/*
            skip_cleanup: true
            on:
                tags: true

install:
    - sudo chmod o+rw /dev/kvm
    - curl https://nixos.org/nix/install | sh
    - . /home/travis/.nix-profile/etc/profile.d/nix.sh
    - sudo mkdir -p /etc/nix
    - echo "binary-caches = https://cache.nixos.org https://xtruder-public.cachix.org" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= xtruder-public.cachix.org-1:+qG/fM2195QJcE2BXmKC+sS4mX/lQHqwjBH83Rhzl14=" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo "system-features = nixos-test benchmark big-parallel kvm" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf > /dev/null

    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix use xtruder-public
    - nix-env -f https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz -iA nixFlakes

before_script:
    - if [ -n "$CACHIX_SIGNING_KEY" ]; then cachix push xtruder-public --watch-store; fi &

script:
   - nix build .#$TARGET
