name: Build images
on: [pull_request, push]
jobs:
    build_hyperv_image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: cachix/install-nix-action@v7
            - uses: cachix/cachix-action@v5
              with:
                name: xtruder-public
                signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
                authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
                attributes: images.hyperv-image
            - name: upload image to artifacts
              uses: actions/upload-artifact@v1
              with:
                name: hyperv-image
                path: result/disk.vhdx
